name: nassem
description: Nassem Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  #localization
  flutter_localizations:
    sdk: flutter
  #UI Packages
  syncfusion_flutter_charts: ^20.4.41
  flutter_slidable: ^2.0.0
  tab_indicator_styler: ^2.0.0
  dropdown_search: ^5.0.3
  pin_code_fields: ^7.4.0
  auto_size_text: ^3.0.0
  search_choices: ^2.1.5
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  blur: ^3.1.0
  #Helpers
  scan: ^1.6.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^1.1.6
  get: ^4.6.5
  dio: ^4.0.6
  ansi_logger: ^2.0.11
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.6
  get_storage: ^2.0.3
  connectivity_plus: ^3.0.2
  intl: ^0.17.0
  #Firebase
  fcm_config: ^3.5.0
  flutter_lints: ^2.0.0
  firebase_core: ^2.4.0
  firebase_remote_config: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  #FixPackagesError
dependency_overrides:
  firebase_core_platform_interface: ^4.5.2
flutter:
  uses-material-design: true
  #Assets
  assets:
    - assets/images/
  #Fonts
  fonts:
    - family: Montserrat-Arabic
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_Bahij_TheSansArabic-Bold.ttf
          weight: 900
        - asset: assets/fonts/alfont_com_AlFont_com_Bahij_TheSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/alfont_com_AlFont_com_Bahij_TheSansArabic-Bold.ttf
          weight: 800
        - asset: assets/fonts/alfont_com_Bahij_TheSansArabic-Plain.ttf
          weight: 300
        - asset: assets/fonts/alfont_com_Bahij_TheSansArabic-Plain.ttf
          weight: 500
        - asset: assets/fonts/alfont_com_Bahij_TheSansArabic-Plain.ttf
          weight: 400
        - asset: assets/fonts/alfont_com_Bahij_TheSansArabic-Plain.ttf
          weight: 600
